FROM mcr.microsoft.com/playwright/python:v1.59.0-noble
WORKDIR /app

ARG PYPI_MIRROR=https://pypi.org/simple

COPY backend/pyproject.toml ./
COPY backend/app/ ./app/
COPY chrome-linux/ /app/chrome-linux/
ENV PLAYWRIGHT_CHROMIUM_PATH=/app/chrome-linux/chrome
RUN pip install --no-cache-dir --progress-bar off -i ${PYPI_MIRROR} hatchling && \
    pip install --no-cache-dir --progress-bar off -i ${PYPI_MIRROR} --no-build-isolation .
EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
